language: ruby
bundler_args: --without development production
sudo: false
rvm:
- 2.3.0
script:
- RAILS_ENV=test bundle exec rake db:setup spec
notifications:
  email:
    recipients:
    - jorgevp5@gmail.com
    on_success: change
    on_failure: always
addons:
  postgresql: "9.5"
